#!/bin/bash
rm -f ackinstall
apt update -y && apt upgrade -y
clear
wget https://raw.githubusercontent.com/twossh/SSHPLUS/master/Plus > /dev/null 2>&1
chmod +x Plus; ./Plus
clear

echo -e "\033[01;31m===================================================================="
echo -e " \033[1;33m[ INSTALANDO PACOTES... ] \033[1;33m"
echo -e "\033[01;31m===================================================================="

#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
 ### "APT INSTALL"
apt install htop -y > /dev/null 2>&1
apt install net-tools -y > /dev/null 2>&1
apt install sysstat -y > /dev/null 2>&1
apt install slurm -y > /dev/null 2>&1
apt install intel-microcode -y > /dev/null 2>&1
apt install haveged -y > /dev/null 2>&1
apt install tuned -y > /dev/null 2>&1
apt autoremove -y > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
### "SERVICE SSHD" ###
echo -n > /etc/ssh/sshd_config
echo "X11Forwarding yes" >> /etc/ssh/sshd_config
echo "PrintMotd no" >> /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
echo "Subsystem       sftp    /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "Compression yes" >> /etc/ssh/sshd_config
echo "UseDNS yes" >> /etc/ssh/sshd_config
echo "UsePAM yes" >> /etc/ssh/sshd_config
echo "Authenticationmethods password" >> /etc/ssh/sshd_config
echo "Kexalgorithms diffie-hellman-group14-sha1" >> /etc/ssh/sshd_config
echo "Ciphers aes128-ctr" >> /etc/ssh/sshd_config
echo "ClientAliveCountMax 7200" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 120s" >> /etc/ssh/sshd_config
echo "MaxStartups 20000" >> /etc/ssh/sshd_config
echo "MaxSessions 20000" >> /etc/ssh/sshd_config
echo "MaxAuthTries 20000" >> /etc/ssh/sshd_config
echo "LoginGraceTime 0" >> /etc/ssh/sshd_config
echo "TCPKeepAlive yes" >> /etc/ssh/sshd_config
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "RC.LOCAL" ###
echo -n > /etc/rc.local
chmod +x /etc/rc.local
echo "#!/bin/sh -e" >> /etc/rc.local
echo "/sbin/ifconfig eth0 mtu 9000" >> /etc/rc.local
echo "/sbin/ip link set eth0 txqueuelen 13888" >> /etc/rc.local
echo "/sbin/ip route | while read p; do ip route change $p initcwnd 25 initrwnd 25; done" >> /etc/rc.local
echo "ethtool -G eth0 rx 3502" >> /etc/rc.local
echo "ethtool -G eth0 tx 2048" >> /etc/rc.local
echo "bash -c 'echo 1 > /sys/module/processor/parameters/ignore_ppc'" >> /etc/rc.local
echo "bash -c 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'" >> /etc/rc.local
echo "bash -c 'echo 2000000 > $x/scaling_max_freq'" >> /etc/rc.local
echo "echo deadline > /sys/block/sda/queue/scheduler" >> /etc/rc.local
echo "echo 16834 > /sys/block/sda/queue/read_ahead_kb" >> /etc/rc.local
echo "echo 2024 > /sys/block/sda/queue/nr_requests" >> /etc/rc.local
echo "echo 0 > /sys/block/sda/queue/rotational" >> /etc/rc.local
echo "echo echo never > /sys/kernel/mm/transparent_hugepage/enabled" >> /etc/rc.local
echo "blockdev --setra 8192 /dev/sda" >> /etc/rc.local
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "CRONTAB" ###
cd /bin/ && wget https://www.dropbox.com/s/1eo8dpza8fe7stb/ackclear > /dev/null 2>&1
cd /bin/ && wget https://www.dropbox.com/s/8ugv70ys1ixtb4a/acksyshttpack > /dev/null 2>&1
cd /bin/ && chmod +x ackclear
cd /bin/ && chmod +x acksyshttpack
crontab -r > /dev/null 2>&1
(crontab -l; echo "@daily /sbin/fstrim -a || true") | crontab - > /dev/null 2>&1
(crontab -l; echo "@daily /bin/ackclear") | crontab - > /dev/null 2>&1
(crontab -l; echo "@daily /bin/uexpired") | crontab - > /dev/null 2>&1
(crontab -l; echo "@reboot /bin/acksyshttpack") | crontab - > /dev/null 2>&1
(crontab -l; echo "@reboot /etc/autostart") | crontab - > /dev/null 2>&1
(crontab -l; echo "@monthly /sbin/reboot") | crontab - > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
rm /etc/resolv.conf
echo "search www.google.com" >> /etc/resolv.conf
echo "options timeout:1 attempts:1 rotate" >> /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf
chmod +x /etc/resolv.conf
chattr +i /etc/resolv.conf > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "SWAPPING" ###
fallocate -l 8G /swapfile > /dev/null 2>&1
chmod 600 /swapfile > /dev/null 2>&1
mkswap /swapfile > /dev/null 2>&1
swapon /swapfile > /dev/null 2>&1
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "SECURITY LIMITS" ###
echo -n > /etc/security/limits.conf
echo "root soft nproc unlimited" >> /etc/security/limits.conf
echo "root hard nproc unlimited" >> /etc/security/limits.conf
echo "root soft nofile 1048576" >> /etc/security/limits.conf
echo "root hard nofile 1048576" >> /etc/security/limits.conf
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "TUNED ADM ACTIVE" ###
mkdir /etc/tuned/ACKHTTP > /dev/null 2>&1
touch /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "[main]" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "[cpu]" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "governor=performance" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "energy_perf_bias=performance" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "min_perf_pct=100" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "[disk]" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "readahead=4096" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "[bootloader]" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
echo "cmdline=skew_tick=1" >> /etc/tuned/ACKHTTP/tuned.conf > /dev/null 2>&1
tuned-adm profile ACKHTTP > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "HAVEGED" ###
echo -n > /etc/default/haveged
echo "DAEMON_ARGS="-w 65535"" >> /etc/default/haveged
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "SSHPLUS MODY ACKHTTP" ###
cd /bin/ && rm -f menu > /dev/null 2>&1
cd /bin/ && rm -f sshmonitor > /dev/null 2>&1
cd /bin/ && rm -f detalhes > /dev/null 2>&1
cd /bin/ && rm -f infousers > /dev/null 2>&1
cd /etc/SSHPlus && rm -rf wsproxy.py
cd /bin/ && wget https://www.dropbox.com/s/9rnfn8nj8joxvkx/menu > /dev/null 2>&1
cd /bin/ && wget https://www.dropbox.com/s/nf3x2hjsgwvk6iw/sshmonitor > /dev/null 2>&1
cd /bin/ && wget https://www.dropbox.com/s/91yopv427wvqghf/detalhes > /dev/null 2>&1
cd /bin/ && wget https://www.dropbox.com/s/f3hxxj6wrd93ifs/infousers > /dev/null 2>&1
cd /etc/SSHPlus && wget https://www.dropbox.com/s/49b147o626utoqv/wsproxy.py > /dev/null 2>&1
cd /bin/ && chmod +x menu
cd /bin/ && chmod +x sshmonitor
cd /bin/ && chmod +x detalhes
cd /bin/ && chmod +x infousers
cd /etc/SSHPlus && chmod +x wsproxy.py
echo "netstat -tlpn | grep -w 80 > /dev/null || {  screen -r -S 'wsproxy' -X quit;  screen -dmS wsproxy python /etc/SSHPlus/wsproxy.py 80; }" >> /etc/autostart
grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
echo "menu;" >> /etc/profile
#######################################
#### "FIM" ####
clear

echo -e "\033[01;31m===================================================================="
echo -e " \033[1;32m[ TODOS OS PACOTES CONCLUIDOS! ! ] \033[1;33m"
echo -e ""
echo -e " \033[1;32m[ SERVIDOR REINICIANDO EM 10s ...  ]"
echo -e "\033[01;31m===================================================================="


sleep 10s;reboot
